"""Tests cho PostgreSQL DDL codegen và cấu hình provider."""

from src.domain.sandbox.enums import SandboxDbType
from src.infrastructure.codegen.pydbml_artifact_generator import PyDbmlDdlGenerator
from src.infrastructure.llm.factory import OPENROUTER_BASE_URL, resolve_provider_config

DBML = """Table rides {
  ride_id int [pk, increment]
  driver_id int [not null]
  amount decimal(10,2)
}

Table drivers {
  driver_id int [pk]
  name varchar(100)
}

Ref: rides.driver_id > drivers.driver_id"""


def test_postgresql_codegen_uses_identity_not_sqlite_autoincrement() -> None:
    ddl = PyDbmlDdlGenerator().generate_ddl(DBML, SandboxDbType.POSTGRESQL)
    assert 'CREATE TABLE "rides"' in ddl
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
    assert "AUTOINCREMENT" not in ddl
    assert 'REFERENCES "drivers"' in ddl

def test_openrouter_credentials_select_compatible_endpoint_and_model_slug() -> None:
    base_url, model_name = resolve_provider_config(
        "sk-or-v1-test",
        "",
        "gpt-4o-mini",
    )

    assert base_url == OPENROUTER_BASE_URL
    assert model_name == "openai/gpt-4o-mini"


def test_local_ollama_10b_14b_config_initialization() -> None:
    base_url, model_name = resolve_provider_config(
        "ollama",
        "http://localhost:11434/v1",
        "qwen2.5-coder:14b",
    )

    assert base_url == "http://localhost:11434/v1"
    assert model_name == "qwen2.5-coder:14b"
