"""Tests cho UC5.3 insight và UC5.4 PostgreSQL DDL codegen."""

from unittest.mock import AsyncMock
from uuid import uuid4

import pytest
from src.application.common.unit_of_work import IUnitOfWork
from src.application.data_models.data_model_service import DataModelService
from src.application.data_models.input import GetDataModelInput
from src.application.data_models.insight_analyzer import IDataModelInsightAnalyzer
from src.application.data_models.output import DataModelInsightOutput
from src.domain.data_model.entities import DataModel
from src.domain.data_model.repository import IDataModelRepository
from src.infrastructure.codegen.pydbml_artifact_generator import PyDbmlArtifactGenerator
from src.infrastructure.llm.data_model_insight_analyzer import (
    OPENROUTER_BASE_URL,
    LlmDataModelInsight,
    LlmDataModelInsightAnalyzer,
    LlmDataModelInsightBatch,
)

DBML = """Table rides {
  ride_id int [pk, increment]
  driver_id int [not null]
  amount decimal(10,2)
}

Table drivers {
  driver_id int [pk]
  name varchar(100)
}

Ref: rides.driver_id > drivers.driver_id"""


class FakeStructuredLlm:
    def __init__(self, result=None, error: Exception | None = None) -> None:
        self.result = result
        self.error = error
        self.messages = None

    async def ainvoke(self, input):
        self.messages = input
        if self.error is not None:
            raise self.error
        return self.result


def test_postgresql_codegen_uses_identity_not_sqlite_autoincrement() -> None:
    ddl = PyDbmlArtifactGenerator().generate_ddl(DBML, "postgresql")
    assert 'CREATE TABLE "rides"' in ddl
    assert "GENERATED BY DEFAULT AS IDENTITY" in ddl
    assert "AUTOINCREMENT" not in ddl
    assert 'REFERENCES "drivers"' in ddl


def test_analysis_is_derived_from_current_tables() -> None:
    insights = PyDbmlArtifactGenerator().analyze(DBML)
    assert {item.table_name for item in insights} == {"rides", "drivers"}
    assert any(item.id == "rides:grain" for item in insights)
    assert all(item.table_name != "Fact_Rides" for item in insights)


def test_openrouter_credentials_select_compatible_endpoint_and_model_slug() -> None:
    base_url, model_name = LlmDataModelInsightAnalyzer._resolve_provider_config(
        "sk-or-v1-test",
        "",
        "gpt-4o-mini",
    )

    assert base_url == OPENROUTER_BASE_URL
    assert model_name == "openai/gpt-4o-mini"


def test_local_ollama_10b_14b_config_initialization() -> None:
    base_url, model_name = LlmDataModelInsightAnalyzer._resolve_provider_config(
        "ollama",
        "http://localhost:11434/v1",
        "qwen2.5-coder:14b",
    )

    assert base_url == "http://localhost:11434/v1"
    assert model_name == "qwen2.5-coder:14b"



@pytest.mark.asyncio
async def test_llm_analysis_returns_only_grounded_confident_insights() -> None:
    llm = FakeStructuredLlm(
        LlmDataModelInsightBatch(
            insights=[
                LlmDataModelInsight(
                    id="rides:foreign-key",
                    table_name="RIDES",
                    severity="info",
                    title="Quan hệ driver hợp lệ",
                    description="Bảng rides tham chiếu bảng drivers.",
                    evidence=["rides.driver_id -> drivers.driver_id"],
                    recommendation=None,
                    confidence=0.95,
                ),
                LlmDataModelInsight(
                    id="ghost:invented",
                    table_name="ghost",
                    severity="error",
                    title="Bảng không tồn tại",
                    description="Insight này phải bị loại.",
                    confidence=0.99,
                ),
                LlmDataModelInsight(
                    id="drivers:uncertain",
                    table_name="drivers",
                    severity="warn",
                    title="Nhận xét không chắc chắn",
                    description="Insight này có confidence quá thấp.",
                    confidence=0.2,
                ),
            ]
        )
    )
    analyzer = LlmDataModelInsightAnalyzer(PyDbmlArtifactGenerator(), llm=llm)

    insights = await analyzer.analyze(DBML)

    assert [item.id for item in insights] == ["rides:foreign-key"]
    assert insights[0].table_name == "rides"
    assert "rides.driver_id -> drivers.driver_id" in insights[0].description
    assert llm.messages is not None
    assert "amount" in llm.messages[1].content


@pytest.mark.asyncio
async def test_llm_analysis_falls_back_when_invocation_fails() -> None:
    analyzer = LlmDataModelInsightAnalyzer(
        PyDbmlArtifactGenerator(),
        llm=FakeStructuredLlm(error=TimeoutError("LLM timed out")),
    )

    insights = await analyzer.analyze(DBML)

    assert any(item.id == "rides:grain" for item in insights)


@pytest.mark.asyncio
async def test_llm_analysis_falls_back_without_api_key() -> None:
    analyzer = LlmDataModelInsightAnalyzer(PyDbmlArtifactGenerator(), api_key="")

    insights = await analyzer.analyze(DBML)

    assert any(item.id == "drivers:grain" for item in insights)


@pytest.mark.asyncio
async def test_data_model_service_returns_revision_bound_artifacts() -> None:
    model = DataModel(project_id=uuid4(), dbml=DBML, revision=7)
    repository = AsyncMock(spec=IDataModelRepository)
    repository.get_by_project_id.return_value = model
    service = DataModelService(
        repository,
        AsyncMock(spec=IUnitOfWork),
        PyDbmlArtifactGenerator(),
    )

    ddl = await service.generate_ddl(GetDataModelInput(project_id=model.project_id), "postgresql")
    insights = await service.get_insights(GetDataModelInput(project_id=model.project_id))
    assert ddl.revision == 7
    assert ddl.dialect == "postgresql"
    assert len(insights) >= 2


@pytest.mark.asyncio
async def test_data_model_service_uses_async_insight_analyzer() -> None:
    model = DataModel(project_id=uuid4(), dbml=DBML, revision=2)
    repository = AsyncMock(spec=IDataModelRepository)
    repository.get_by_project_id.return_value = model
    analyzer = AsyncMock(spec=IDataModelInsightAnalyzer)
    analyzer.analyze.return_value = [
        DataModelInsightOutput(
            id="rides:llm",
            table_name="rides",
            severity="info",
            title="LLM insight",
            description="Phân tích từ LLM.",
        )
    ]
    service = DataModelService(
        repository,
        AsyncMock(spec=IUnitOfWork),
        PyDbmlArtifactGenerator(),
        analyzer,
    )

    insights = await service.get_insights(GetDataModelInput(project_id=model.project_id))

    assert insights[0].id == "rides:llm"
    analyzer.analyze.assert_awaited_once_with(DBML)
