"""Ánh xá tập trung từ ErrorCode sang HTTP Status Code tương ứng."""

from http import HTTPStatus

from src.common.exceptions.error_codes import ErrorCode

ERROR_STATUS_MAP: dict[ErrorCode, HTTPStatus] = {
    # Lỗi HTTP tổng quát
    ErrorCode.BAD_REQUEST: HTTPStatus.BAD_REQUEST,
    ErrorCode.RESOURCE_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.METHOD_NOT_ALLOWED: HTTPStatus.METHOD_NOT_ALLOWED,
    # --- Business Domain Errors ---
    ErrorCode.USER_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.PROJECT_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.REQUIREMENT_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.DATA_SOURCE_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.DATA_SOURCE_COLUMN_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.SESSION_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.SESSION_RUN_IN_PROGRESS: HTTPStatus.CONFLICT,
    ErrorCode.DATA_MODEL_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.DATA_MODEL_ALREADY_EXISTS: HTTPStatus.CONFLICT,
    ErrorCode.DATA_MODEL_CHANGE_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.DATA_MODEL_REVISION_INVALID: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_MODEL_REVISION_CONFLICT: HTTPStatus.CONFLICT,
    ErrorCode.DATA_MODEL_CHANGE_ALREADY_PENDING: HTTPStatus.CONFLICT,
    ErrorCode.DATA_MODEL_CHANGE_OUTDATED: HTTPStatus.CONFLICT,
    ErrorCode.ANALYSIS_INPUT_CHANGED: HTTPStatus.CONFLICT,
    ErrorCode.INVALID_REQUIREMENT: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_MODEL_ANALYSIS_OUTDATED: HTTPStatus.CONFLICT,
    ErrorCode.DATA_MODEL_UPDATE_ID_MISMATCH: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- Domain Validation Errors ---
    ErrorCode.INVALID_EMAIL: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_USERNAME: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.USERNAME_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PROJECT_NAME: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.PROJECT_NAME_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PROJECT_REQUIREMENT: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PROJECT_DOMAIN: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_PROJECT_STATUS_TRANSITION: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_REQUIREMENT_TITLE: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.REQUIREMENT_TITLE_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_REQUIREMENT_DESCRIPTION: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_ANALYTICAL_REQUIREMENT_REF: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_DATA_SOURCE_NAME: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_SOURCE_NAME_TOO_LONG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_DATA_SOURCE_LOCATION: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_SESSION_EVENT_REF: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_MODEL_DBML_REQUIRED: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_MODEL_DBML_SYNTAX_INVALID: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_MODEL_VALIDATION_FAILED: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.DATA_MODEL_AGENT_VALIDATION_RETRIES_EXHAUSTED: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_DATA_MODEL_CHANGE_STATUS_TRANSITION: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- File Upload Errors ---
    ErrorCode.INVALID_FILE_FORMAT: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.MAX_FILES_EXCEEDED: HTTPStatus.BAD_REQUEST,
    ErrorCode.FILE_PARSING_ERROR: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.FILE_EMPTY: HTTPStatus.BAD_REQUEST,
    ErrorCode.FILE_TOO_LARGE: HTTPStatus.REQUEST_ENTITY_TOO_LARGE,
    # --- Sandbox Errors ---
    ErrorCode.SANDBOX_CONFIG_NOT_FOUND: HTTPStatus.NOT_FOUND,
    ErrorCode.SANDBOX_CONNECTION_FAILED: HTTPStatus.BAD_REQUEST,
    ErrorCode.SANDBOX_EXECUTION_ERROR: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.INVALID_SANDBOX_CONFIG: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.UNSUPPORTED_SANDBOX_DB_TYPE: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.UNSUPPORTED_DDL_DIALECT: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- General Validation Errors ---
    ErrorCode.VALIDATION_ERROR: HTTPStatus.UNPROCESSABLE_ENTITY,
    # --- Authentication Errors ---
    ErrorCode.AUTHENTICATION_REQUIRED: HTTPStatus.UNAUTHORIZED,
    ErrorCode.INVALID_CREDENTIALS: HTTPStatus.UNAUTHORIZED,
    ErrorCode.TOKEN_EXPIRED: HTTPStatus.UNAUTHORIZED,
    ErrorCode.TOKEN_INVALID: HTTPStatus.UNAUTHORIZED,
    # --- Authorization Errors ---
    ErrorCode.PERMISSION_DENIED: HTTPStatus.FORBIDDEN,
    # --- System / Infrastructure Errors ---
    ErrorCode.DATABASE_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.REDIS_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.STORAGE_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.LLM_ERROR: HTTPStatus.BAD_GATEWAY,
    ErrorCode.LLM_MODEL_NOT_FOUND: HTTPStatus.BAD_GATEWAY,
    ErrorCode.LLM_AUTHENTICATION_ERROR: HTTPStatus.BAD_GATEWAY,
    ErrorCode.LLM_RATE_LIMIT_ERROR: HTTPStatus.BAD_GATEWAY,
    ErrorCode.LLM_QUOTA_EXCEEDED: HTTPStatus.BAD_GATEWAY,
    ErrorCode.LLM_TIMEOUT_ERROR: HTTPStatus.GATEWAY_TIMEOUT,
    ErrorCode.LLM_STRUCTURED_OUTPUT_ERROR: HTTPStatus.BAD_GATEWAY,
    ErrorCode.LLM_PII_DEGRADATION_ERROR: HTTPStatus.UNPROCESSABLE_ENTITY,
    ErrorCode.AGENT_EXECUTION_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
    ErrorCode.EXTERNAL_SERVICE_ERROR: HTTPStatus.BAD_GATEWAY,
    ErrorCode.INTERNAL_SERVER_ERROR: HTTPStatus.INTERNAL_SERVER_ERROR,
}

HTTP_ERROR_CODE_MAP: dict[HTTPStatus, ErrorCode] = {
    HTTPStatus.BAD_REQUEST: ErrorCode.BAD_REQUEST,
    HTTPStatus.UNAUTHORIZED: ErrorCode.AUTHENTICATION_REQUIRED,
    HTTPStatus.FORBIDDEN: ErrorCode.PERMISSION_DENIED,
    HTTPStatus.NOT_FOUND: ErrorCode.RESOURCE_NOT_FOUND,
    HTTPStatus.METHOD_NOT_ALLOWED: ErrorCode.METHOD_NOT_ALLOWED,
    HTTPStatus.UNPROCESSABLE_ENTITY: ErrorCode.VALIDATION_ERROR,
}


def get_http_status_code(code: ErrorCode) -> HTTPStatus:
    """Tra cứu HTTP Status tương ứng với ErrorCode.

    Args:
        code: ErrorCode cần tra cứu.

    Returns:
        HTTPStatus: Mã trạng thái HTTP tương ứng, mặc định là 500 nếu chưa được định nghĩa.
    """
    return ERROR_STATUS_MAP.get(code, HTTPStatus.INTERNAL_SERVER_ERROR)


def get_error_code_for_http_status(status_code: int) -> ErrorCode:
    """Ánh xạ HTTP status tại presentation boundary sang mã lỗi tổng quát.

    Args:
        status_code: HTTP status cần ánh xạ.

    Returns:
        Mã lỗi tổng quát, không gắn sai ngữ cảnh nghiệp vụ.
    """
    try:
        status = HTTPStatus(status_code)
    except ValueError:
        return ErrorCode.INTERNAL_SERVER_ERROR
    if status.value >= HTTPStatus.INTERNAL_SERVER_ERROR.value:
        return ErrorCode.INTERNAL_SERVER_ERROR
    return HTTP_ERROR_CODE_MAP.get(status, ErrorCode.BAD_REQUEST)
