"""Định nghĩa danh sách Error Codes chuẩn của toàn bộ hệ thống backend."""

from enum import StrEnum


class ErrorCode(StrEnum):
    """Mã lỗi chuẩn hóa cho toàn hệ thống (dạng UPPER_SNAKE_CASE)."""

    # Lỗi HTTP tổng quát tại presentation boundary
    BAD_REQUEST = "BAD_REQUEST"
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"

    # --- Business Domain Error Codes ---
    USER_NOT_FOUND = "USER_NOT_FOUND"
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    REQUIREMENT_NOT_FOUND = "REQUIREMENT_NOT_FOUND"
    REQUIREMENT_FILE_NOT_FOUND = "REQUIREMENT_FILE_NOT_FOUND"
    REQUIREMENT_REVISION_CONFLICT = "REQUIREMENT_REVISION_CONFLICT"
    REQUIREMENT_CONTEXT_EMPTY = "REQUIREMENT_CONTEXT_EMPTY"
    REQUIREMENT_CONTINUATION_INVALID = "REQUIREMENT_CONTINUATION_INVALID"
    DATA_SOURCE_NOT_FOUND = "DATA_SOURCE_NOT_FOUND"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_RUN_IN_PROGRESS = "SESSION_RUN_IN_PROGRESS"
    SESSION_CLARIFICATION_PENDING = "SESSION_CLARIFICATION_PENDING"
    SESSION_CLARIFICATION_STALE = "SESSION_CLARIFICATION_STALE"
    SESSION_PURPOSE_MISMATCH = "SESSION_PURPOSE_MISMATCH"
    CONVERSATION_CONTEXT_BUDGET_EXCEEDED = "CONVERSATION_CONTEXT_BUDGET_EXCEEDED"
    DATA_MODEL_NOT_FOUND = "DATA_MODEL_NOT_FOUND"
    DATA_MODEL_ALREADY_EXISTS = "DATA_MODEL_ALREADY_EXISTS"
    DATA_MODEL_CHANGE_NOT_FOUND = "DATA_MODEL_CHANGE_NOT_FOUND"

    DATA_MODEL_REVISION_INVALID = "DATA_MODEL_REVISION_INVALID"
    DATA_MODEL_REVISION_CONFLICT = "DATA_MODEL_REVISION_CONFLICT"
    DATA_MODEL_CHANGE_ALREADY_PENDING = "DATA_MODEL_CHANGE_ALREADY_PENDING"
    DATA_MODEL_CHANGE_OUTDATED = "DATA_MODEL_CHANGE_OUTDATED"
    ANALYSIS_INPUT_CHANGED = "ANALYSIS_INPUT_CHANGED"
    REQUIREMENT_SEMANTIC_CLARIFICATION_REQUIRED = (
        "REQUIREMENT_SEMANTIC_CLARIFICATION_REQUIRED"
    )
    ANALYTICAL_SOURCE_GAP = "ANALYTICAL_SOURCE_GAP"

    INVALID_REQUIREMENT = "INVALID_REQUIREMENT"
    DATA_MODEL_ANALYSIS_OUTDATED = "DATA_MODEL_ANALYSIS_OUTDATED"
    DATA_MODEL_UPDATE_ID_MISMATCH = "DATA_MODEL_UPDATE_ID_MISMATCH"

    # --- Domain Validation Error Codes ---
    # User Domain
    INVALID_EMAIL = "INVALID_EMAIL"
    INVALID_USERNAME = "INVALID_USERNAME"
    USERNAME_TOO_LONG = "USERNAME_TOO_LONG"
    USERNAME_ALREADY_EXISTS = "USERNAME_ALREADY_EXISTS"
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
    WEAK_PASSWORD = "WEAK_PASSWORD"

    # Project Domain
    INVALID_PROJECT_NAME = "INVALID_PROJECT_NAME"
    PROJECT_NAME_TOO_LONG = "PROJECT_NAME_TOO_LONG"
    INVALID_PROJECT_REQUIREMENT = "INVALID_PROJECT_REQUIREMENT"
    INVALID_PROJECT_DOMAIN = "INVALID_PROJECT_DOMAIN"
    INVALID_PROJECT_STATUS_TRANSITION = "INVALID_PROJECT_STATUS_TRANSITION"

    # Requirement Domain
    INVALID_REQUIREMENT_TITLE = "INVALID_REQUIREMENT_TITLE"
    REQUIREMENT_TITLE_TOO_LONG = "REQUIREMENT_TITLE_TOO_LONG"
    INVALID_REQUIREMENT_DESCRIPTION = "INVALID_REQUIREMENT_DESCRIPTION"

    # Analytical Requirement Domain
    INVALID_ANALYTICAL_REQUIREMENT_REF = "INVALID_ANALYTICAL_REQUIREMENT_REF"

    # Data Source Domain
    INVALID_DATA_SOURCE_NAME = "INVALID_DATA_SOURCE_NAME"
    DATA_SOURCE_NAME_TOO_LONG = "DATA_SOURCE_NAME_TOO_LONG"
    INVALID_DATA_SOURCE_LOCATION = "INVALID_DATA_SOURCE_LOCATION"
    DATA_SOURCE_COLUMN_NOT_FOUND = "DATA_SOURCE_COLUMN_NOT_FOUND"

    # Agent Session Domain
    INVALID_SESSION_EVENT_REF = "INVALID_SESSION_EVENT_REF"

    # Data Model Domain
    DATA_MODEL_DBML_REQUIRED = "DATA_MODEL_DBML_REQUIRED"
    DATA_MODEL_DBML_SYNTAX_INVALID = "DATA_MODEL_DBML_SYNTAX_INVALID"
    DATA_MODEL_VALIDATION_FAILED = "DATA_MODEL_VALIDATION_FAILED"
    DATA_MODEL_AGENT_VALIDATION_RETRIES_EXHAUSTED = "DATA_MODEL_AGENT_VALIDATION_RETRIES_EXHAUSTED"
    INVALID_DATA_MODEL_CHANGE_STATUS_TRANSITION = "INVALID_DATA_MODEL_CHANGE_STATUS_TRANSITION"

    # File / Upload Domain
    INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT"
    MAX_FILES_EXCEEDED = "MAX_FILES_EXCEEDED"
    FILE_PARSING_ERROR = "FILE_PARSING_ERROR"
    FILE_EMPTY = "FILE_EMPTY"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"

    # Sandbox Domain
    SANDBOX_CONFIG_NOT_FOUND = "SANDBOX_CONFIG_NOT_FOUND"
    SANDBOX_CONNECTION_FAILED = "SANDBOX_CONNECTION_FAILED"
    SANDBOX_EXECUTION_ERROR = "SANDBOX_EXECUTION_ERROR"
    INVALID_SANDBOX_CONFIG = "INVALID_SANDBOX_CONFIG"
    UNSUPPORTED_SANDBOX_DB_TYPE = "UNSUPPORTED_SANDBOX_DB_TYPE"
    UNSUPPORTED_DDL_DIALECT = "UNSUPPORTED_DDL_DIALECT"

    # --- General Validation Error Code ---
    VALIDATION_ERROR = "VALIDATION_ERROR"

    # --- Authentication Error Codes ---
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"

    # --- Authorization Error Code ---
    PERMISSION_DENIED = "PERMISSION_DENIED"

    # --- System / Infrastructure Error Codes ---
    DATABASE_ERROR = "DATABASE_ERROR"
    REDIS_ERROR = "REDIS_ERROR"
    STORAGE_ERROR = "STORAGE_ERROR"

    LLM_ERROR = "LLM_ERROR"
    LLM_MODEL_NOT_FOUND = "LLM_MODEL_NOT_FOUND"
    LLM_AUTHENTICATION_ERROR = "LLM_AUTHENTICATION_ERROR"
    LLM_RATE_LIMIT_ERROR = "LLM_RATE_LIMIT_ERROR"
    LLM_QUOTA_EXCEEDED = "LLM_QUOTA_EXCEEDED"
    LLM_CREDENTIALS_EXHAUSTED = "LLM_CREDENTIALS_EXHAUSTED"
    LLM_TIMEOUT_ERROR = "LLM_TIMEOUT_ERROR"
    LLM_STRUCTURED_OUTPUT_ERROR = "LLM_STRUCTURED_OUTPUT_ERROR"
    LLM_PII_DEGRADATION_ERROR = "LLM_PII_DEGRADATION_ERROR"
    AGENT_EXECUTION_ERROR = "AGENT_EXECUTION_ERROR"

    EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"

    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
