"""Kiểm thử use case và API xem mã DDL."""

import pytest
from fastapi import FastAPI
from httpx import ASGITransport, AsyncClient
from src.application.data_models.view_ddl_service import ViewDdlService
from src.common.exceptions import BusinessException, ErrorCode, register_exception_handlers
from src.domain.data_model.entities import DataModelSnapshot
from src.domain.data_model.enums import DdlDialect
from src.presentation.api.router import api_router

SAMPLE_DBML = """
Table Fact_Rides {
  ride_key bigint [pk, increment, not null]
  driver_key int [ref: > Dim_Driver.driver_key, not null]
  fare_amount decimal(12,2) [not null]
}
Table Dim_Driver {
  driver_key int [pk, increment, not null]
  full_name varchar(100)
}
"""


def test_service_generates_postgresql_ddl() -> None:
    """Service sinh đúng bảng, khóa và identity cho PostgreSQL."""
    model = DataModelSnapshot(name="Ride Analytics", revision=12, dbml=SAMPLE_DBML)

    document = ViewDdlService().execute(model, DdlDialect.POSTGRESQL)

    assert document.table_count == 2
    assert 'CREATE TABLE "Fact_Rides"' in document.content
    assert "GENERATED BY DEFAULT AS IDENTITY" in document.content
    assert 'REFERENCES "Dim_Driver" ("driver_key")' in document.content


def test_service_rejects_model_without_tables() -> None:
    """Service từ chối DBML không chứa bảng hợp lệ."""
    model = DataModelSnapshot(name="Empty", revision=1, dbml="Project empty {}")

    with pytest.raises(BusinessException) as captured:
        ViewDdlService().execute(model, DdlDialect.POSTGRESQL)

    assert captured.value.code is ErrorCode.INVALID_DATA_MODEL


def test_service_maps_snowflake_types() -> None:
    """Service ánh xạ identity và numeric đúng cho Snowflake."""
    model = DataModelSnapshot(name="Ride Analytics", revision=12, dbml=SAMPLE_DBML)

    document = ViewDdlService().execute(model, DdlDialect.SNOWFLAKE)

    assert "AUTOINCREMENT START 1 INCREMENT 1" in document.content
    assert '"fare_amount" NUMBER(12,2)' in document.content


@pytest.mark.asyncio
async def test_view_ddl_endpoint_returns_standard_envelope() -> None:
    """API trả đúng response envelope và cú pháp BigQuery."""
    app = FastAPI()
    register_exception_handlers(app)
    app.include_router(api_router)
    transport = ASGITransport(app=app)
    payload = {"model_name": "Ride Analytics", "revision": 12, "dialect": "bigquery", "dbml": SAMPLE_DBML}

    async with AsyncClient(transport=transport, base_url="http://test") as client:
        response = await client.post("/api/v1/data-models/ddl", json=payload)

    body = response.json()
    assert response.status_code == 200
    assert body["status"] == "success"
    assert body["data"]["table_count"] == 2
    assert "INT64" in body["data"]["content"]
    assert "NOT ENFORCED" in body["data"]["content"]
