"""Kiểm thử bộ sinh mã DDL cho cả ba hệ quản trị CSDL được hỗ trợ."""

import pytest
from src.common.exceptions.business import BusinessException
from src.common.exceptions.error_codes import ErrorCode
from src.domain.data_model.enums import SqlDialect
from src.infrastructure.codegen.constants import DEFAULT_SANDBOX_SCHEMA
from src.infrastructure.codegen.ddl_generator import DbmlDdlGenerator


@pytest.fixture
def generator() -> DbmlDdlGenerator:
    """Bộ sinh mã DDL dùng cho toàn bộ bài kiểm thử."""
    return DbmlDdlGenerator()


@pytest.mark.parametrize("dialect", list(SqlDialect))
def test_generate_returns_all_tables(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str, dialect: SqlDialect
) -> None:
    """Mọi dialect đều sinh đủ 3 bảng của mô hình mẫu."""
    result = generator.generate(ride_hailing_dbml, dialect)

    assert result.table_count == 3
    assert result.dialect is dialect
    for table in ("Fact_Rides", "Dim_Driver", "Dim_Customer"):
        assert table in result.ddl


@pytest.mark.parametrize("dialect", list(SqlDialect))
def test_every_table_is_prefixed_with_sandbox_schema(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str, dialect: SqlDialect
) -> None:
    """FR6.1: mọi câu lệnh tạo bảng đều phải gắn tiền tố schema Sandbox."""
    result = generator.generate(ride_hailing_dbml, dialect)

    create_table_lines = [
        line for line in result.ddl.splitlines() if "CREATE" in line and "TABLE" in line
    ]
    assert len(create_table_lines) == 3
    assert all(DEFAULT_SANDBOX_SCHEMA in line for line in create_table_lines)
    assert result.schema_name == DEFAULT_SANDBOX_SCHEMA


@pytest.mark.parametrize("dialect", list(SqlDialect))
def test_dimension_tables_are_created_before_fact_tables(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str, dialect: SqlDialect
) -> None:
    """Bảng Dimension phải được tạo trước bảng Fact để khóa ngoại luôn hợp lệ."""
    ddl = generator.generate(ride_hailing_dbml, dialect).ddl

    assert ddl.index("Dim_Driver") < ddl.index("CREATE OR REPLACE TABLE `sandbox_dwh.Fact_Rides`") \
        if dialect is SqlDialect.BIGQUERY \
        else ddl.index("Dim_Driver") < ddl.index("Fact_Rides")


def test_custom_schema_name_is_applied(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str
) -> None:
    """Cho phép ghi đè tên schema Sandbox qua tham số."""
    result = generator.generate(ride_hailing_dbml, SqlDialect.POSTGRESQL, "sandbox_demo")

    assert result.schema_name == "sandbox_demo"
    assert "CREATE SCHEMA IF NOT EXISTS sandbox_demo;" in result.ddl
    assert DEFAULT_SANDBOX_SCHEMA not in result.ddl


# --- PostgreSQL ---------------------------------------------------------------


def test_postgresql_types_and_constraints(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str
) -> None:
    """PostgreSQL dùng INTEGER/NUMERIC/VARCHAR/TIMESTAMP và IDENTITY cho cột tự tăng."""
    ddl = generator.generate(ride_hailing_dbml, SqlDialect.POSTGRESQL).ddl

    assert "CREATE TABLE IF NOT EXISTS sandbox_dwh." in ddl
    assert "ride_key INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL" in ddl
    assert "fare_amount NUMERIC(10, 2)" in ddl
    assert "trip_status VARCHAR(20)" in ddl
    assert "created_at TIMESTAMP" in ddl
    assert "PRIMARY KEY (ride_key)" in ddl
    assert "NOT ENFORCED" not in ddl


def test_postgresql_emits_alter_table_foreign_keys(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str
) -> None:
    """PostgreSQL khai báo khóa ngoại bằng ALTER TABLE sau khi mọi bảng đã tồn tại."""
    ddl = generator.generate(ride_hailing_dbml, SqlDialect.POSTGRESQL).ddl

    assert ddl.count("ADD CONSTRAINT") == 2
    assert 'REFERENCES sandbox_dwh."Dim_Driver" (driver_key)' in ddl
    assert 'REFERENCES sandbox_dwh."Dim_Customer" (customer_key)' in ddl
    assert ddl.index("CREATE TABLE") < ddl.index("ALTER TABLE")


def test_postgresql_emits_enum_type() -> None:
    """PostgreSQL sinh CREATE TYPE cho khối Enum của DBML."""
    dbml = """
    Enum trip_status {
      completed
      cancelled
    }
    Table Fact_Rides {
      ride_key int [pk]
      status trip_status
    }
    """
    result = DbmlDdlGenerator().generate(dbml, SqlDialect.POSTGRESQL)

    assert "CREATE TYPE sandbox_dwh.trip_status AS ENUM ('completed', 'cancelled');" in result.ddl
    assert "status sandbox_dwh.trip_status" in result.ddl


def test_postgresql_emits_indexes() -> None:
    """PostgreSQL chuyển khối `indexes` của DBML thành câu lệnh CREATE INDEX."""
    dbml = """
    Table Fact_Rides {
      ride_key int [pk]
      driver_key int
      indexes {
        driver_key [name: 'idx_rides_driver']
      }
    }
    """
    ddl = DbmlDdlGenerator().generate(dbml, SqlDialect.POSTGRESQL).ddl

    assert "CREATE INDEX IF NOT EXISTS idx_rides_driver" in ddl
    assert 'ON sandbox_dwh."Fact_Rides" (driver_key);' in ddl


# --- Snowflake ----------------------------------------------------------------


def test_snowflake_types_and_create_or_replace(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str
) -> None:
    """Snowflake dùng CREATE OR REPLACE TABLE, NUMBER, TIMESTAMP_NTZ và AUTOINCREMENT."""
    ddl = generator.generate(ride_hailing_dbml, SqlDialect.SNOWFLAKE).ddl

    assert "CREATE OR REPLACE TABLE sandbox_dwh." in ddl
    assert "ride_key NUMBER(38,0) AUTOINCREMENT NOT NULL" in ddl
    assert "fare_amount NUMBER(10, 2)" in ddl
    assert "created_at TIMESTAMP_NTZ" in ddl
    assert "INTEGER" not in ddl
    assert "NOT ENFORCED" not in ddl


def test_snowflake_skips_indexes_with_warning() -> None:
    """Snowflake không hỗ trợ CREATE INDEX nên phải bỏ qua kèm cảnh báo rõ ràng."""
    dbml = """
    Table Fact_Rides {
      ride_key int [pk]
      driver_key int
      indexes {
        driver_key
      }
    }
    """
    result = DbmlDdlGenerator().generate(dbml, SqlDialect.SNOWFLAKE)

    assert "CREATE INDEX" not in result.ddl
    assert any("CREATE INDEX" in warning for warning in result.warnings)


# --- BigQuery -----------------------------------------------------------------


def test_bigquery_types_and_not_enforced_constraints(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str
) -> None:
    """BigQuery dùng INT64/STRING, khóa chính và khóa ngoại inline kèm NOT ENFORCED."""
    result = generator.generate(ride_hailing_dbml, SqlDialect.BIGQUERY)

    assert "CREATE OR REPLACE TABLE `sandbox_dwh.Fact_Rides`" in result.ddl
    assert "ride_key INT64 NOT NULL" in result.ddl
    assert "trip_status STRING" in result.ddl
    assert result.ddl.count("NOT ENFORCED") == 5
    assert "ALTER TABLE" not in result.ddl


def test_bigquery_drops_increment_with_warning(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str
) -> None:
    """BigQuery không có cột tự tăng nên phải bỏ thuộc tính `increment` kèm cảnh báo."""
    result = generator.generate(ride_hailing_dbml, SqlDialect.BIGQUERY)

    assert "AUTOINCREMENT" not in result.ddl
    assert "IDENTITY" not in result.ddl
    assert any("tự tăng" in warning for warning in result.warnings)


def test_bigquery_converts_indexes_into_cluster_by() -> None:
    """BigQuery chuyển khối `indexes` của DBML thành mệnh đề CLUSTER BY."""
    dbml = """
    Table Fact_Rides {
      ride_key int [pk]
      driver_key int
      customer_key int
      indexes {
        (driver_key, customer_key)
      }
    }
    """
    result = DbmlDdlGenerator().generate(dbml, SqlDialect.BIGQUERY)

    assert "CLUSTER BY driver_key, customer_key;" in result.ddl
    assert "CREATE INDEX" not in result.ddl


def test_bigquery_drops_unique_constraint_with_warning() -> None:
    """BigQuery không hỗ trợ ràng buộc UNIQUE nên phải bỏ kèm cảnh báo."""
    dbml = """
    Table Dim_Driver {
      driver_key int [pk]
      driver_natural_id varchar(50) [unique]
    }
    """
    result = DbmlDdlGenerator().generate(dbml, SqlDialect.BIGQUERY)

    assert "UNIQUE" not in result.ddl
    assert any("UNIQUE" in warning for warning in result.warnings)


# --- Xử lý lỗi ----------------------------------------------------------------


@pytest.mark.parametrize("dialect", list(SqlDialect))
def test_generate_rejects_empty_dbml(
    generator: DbmlDdlGenerator, dialect: SqlDialect
) -> None:
    """DBML rỗng bị từ chối với mã lỗi nghiệp vụ chuẩn ở mọi dialect."""
    with pytest.raises(BusinessException) as exc_info:
        generator.generate("   ", dialect)

    assert exc_info.value.code == ErrorCode.INVALID_DBML_CONTENT


def test_generated_ddl_contains_sandbox_warning_header(
    generator: DbmlDdlGenerator, ride_hailing_dbml: str
) -> None:
    """Script DDL luôn mở đầu bằng khối chú thích cảnh báo chỉ dùng cho Sandbox."""
    ddl = generator.generate(ride_hailing_dbml, SqlDialect.POSTGRESQL).ddl

    assert ddl.startswith("-- ")
    assert "không chạy trên Production" in ddl
    assert "postgresql" in ddl
