/**
 * Custom Hook chứa toàn bộ State & Logic cho Feature Sandbox Deployment
 */

import { useState } from 'react';
import { TerminalLogEntryDto } from '@/api/model/sandbox.dto';
import { formatSql, copyToClipboard } from '@/common/utils/ddl-formatter';
import { downloadTextFile } from '@/common/utils/file-helpers';

const DEFAULT_DDL = `-- ============================================================
-- Data Warehouse DDL Generated by AI Agent
-- Target Engine: PostgreSQL / Redshift
-- Target Schema: sandbox_dwh
-- ============================================================

CREATE SCHEMA IF NOT EXISTS sandbox_dwh;

-- 1. Dimension Tables
CREATE TABLE sandbox_dwh.Dim_Driver (
    driver_key INT PRIMARY KEY,
    driver_natural_id VARCHAR(50) NOT NULL,
    full_name VARCHAR(100),
    vehicle_type VARCHAR(30),
    rating DECIMAL(3,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sandbox_dwh.Dim_Customer (
    customer_key INT PRIMARY KEY,
    phone_number VARCHAR(20),
    member_tier VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Fact Tables
CREATE TABLE sandbox_dwh.Fact_Rides (
    ride_key INT PRIMARY KEY,
    driver_key INT REFERENCES sandbox_dwh.Dim_Driver(driver_key),
    customer_key INT REFERENCES sandbox_dwh.Dim_Customer(customer_key),
    fare_amount DECIMAL(10,2) NOT NULL,
    discount_amount DECIMAL(10,2) DEFAULT 0.00,
    trip_status VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);`;

export function useSandboxDeploy() {
  const [ddlCode, setDdlCode] = useState<string>(DEFAULT_DDL);
  const [hostConnection, setHostConnection] = useState<string>('localhost:5432 (Isolated Postgres Container)');
  const [databaseSchema, setDatabaseSchema] = useState<string>('sandbox_db / schema: sandbox_dwh');
  
  const [logs, setLogs] = useState<TerminalLogEntryDto[]>([
    { timestamp: new Date().toLocaleTimeString(), message: 'Ready for execution.', type: 'info' },
    { timestamp: new Date().toLocaleTimeString(), message: "Click 'Exec DDL & Deploy Sandbox' to test DDL script.", type: 'info' },
  ]);
  
  const [isDeploying, setIsDeploying] = useState<boolean>(false);

  // Format SQL DDL
  const handleFormatDdl = () => {
    setDdlCode((prev) => formatSql(prev));
  };

  // Copy DDL
  const handleCopyDdl = async () => {
    const success = await copyToClipboard(ddlCode);
    if (success) {
      alert('Đã sao chép DDL vào bộ nhớ tạm!');
    }
  };

  // Download .sql file
  const handleDownloadDdl = () => {
    downloadTextFile('dwh_schema_ddl.sql', ddlCode, 'text/plain');
  };

  // Download .md documentation
  const handleDownloadDoc = () => {
    const mdContent = `# Tài liệu Cấu trúc Data Warehouse DWH\n\n## 1. Tổng quan Schema\nTarget Schema: \`sandbox_dwh\`\n\n## 2. Mã DDL Script\n\`\`\`sql\n${ddlCode}\n\`\`\`\n`;
    downloadTextFile('schema_documentation.md', mdContent, 'text/markdown');
  };

  // Thực thi Deploy Sandbox DDL
  const handleDeploySandbox = () => {
    setIsDeploying(true);
    const now = new Date().toLocaleTimeString();

    setLogs((prev) => [
      ...prev,
      { timestamp: now, message: `Connecting to ${hostConnection}...`, type: 'info' },
    ]);

    setTimeout(() => {
      setLogs((prev) => [
        ...prev,
        { timestamp: new Date().toLocaleTimeString(), message: 'Executing DDL script on target schema...', type: 'info' },
        { timestamp: new Date().toLocaleTimeString(), message: 'CREATE TABLE sandbox_dwh.Dim_Driver [OK]', type: 'success' },
        { timestamp: new Date().toLocaleTimeString(), message: 'CREATE TABLE sandbox_dwh.Dim_Customer [OK]', type: 'success' },
        { timestamp: new Date().toLocaleTimeString(), message: 'CREATE TABLE sandbox_dwh.Fact_Rides [OK]', type: 'success' },
        { timestamp: new Date().toLocaleTimeString(), message: '🚀 Deploy Sandbox thành công! Tất cả bảng DWH sẵn sàng.', type: 'success' },
      ]);
      setIsDeploying(false);
    }, 700);
  };

  // Sinh dữ liệu test
  const handleGenerateTestData = () => {
    const now = new Date().toLocaleTimeString();
    setLogs((prev) => [
      ...prev,
      { timestamp: now, message: '🧪 Generating test mock data (100 rows)...', type: 'info' },
      { timestamp: new Date().toLocaleTimeString(), message: 'Inserted 10 rows into Dim_Driver', type: 'success' },
      { timestamp: new Date().toLocaleTimeString(), message: 'Inserted 30 rows into Dim_Customer', type: 'success' },
      { timestamp: new Date().toLocaleTimeString(), message: 'Inserted 60 rows into Fact_Rides', type: 'success' },
      { timestamp: new Date().toLocaleTimeString(), message: 'Simulated mock data inserted successfully.', type: 'success' },
    ]);
  };

  return {
    ddlCode,
    setDdlCode,
    hostConnection,
    setHostConnection,
    databaseSchema,
    setDatabaseSchema,
    logs,
    isDeploying,
    handleFormatDdl,
    handleCopyDdl,
    handleDownloadDdl,
    handleDownloadDoc,
    handleDeploySandbox,
    handleGenerateTestData,
  };
}
